import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "/dashboard",
    title: "Dashboard",
    icon: "mdi mdi-gauge",
    class: "",
    extralink: false,
    submenu: [],
  }, 
  {
    path: "/dashboard/manage-banner",
    title: "Manage Banner",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-causes",
    title: "Manage Home Causes",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-causes-section",
    title: "Manage Home Causes Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-donation-section",
    title: "Manage Home Donation Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-event-count-section",
    title: "Manage Home Event Count Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-event-list-section",
    title: "Manage Home Event List Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-event-section",
    title: "Manage Home Event Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-home-welcome-section",
    title: "Manage Home Welcome Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-blog",
    title: "Manage Blog",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-blog-comment",
    title: "Manage Blog Comment",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-causes-details",
    title: "Manage Causes Details",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-causes-points",
    title: "Manage Causes Points",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-contact-us-form",
    title: "Manage ContactUs Form",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-contact-us-icon-section",
    title: "Manage ContactUs Icon Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-contact-us-section",
    title: "Manage ContactUs Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-donate-now",
    title: "Manage Donate Now",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-donate-now-form",
    title: "Manage Donate Now Form",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-event",
    title: "Manage Event",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-faq-list",
    title: "Manage Faq List",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-faq-section",
    title: "Manage Faq Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-footer-section-anupam",
    title: "Manage Footer Section Anupam",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-gallery",
    title: "Manage Gallery",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-gender",
    title: "Manage Gender",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-help",
    title: "Manage Help",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },

  {
    path: "/dashboard/manage-latest-news",
    title: "Manage Latest News",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-latest-news-section",
    title: "Manage Latest News Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-mission-and-goals",
    title: "Manage Mission And Goals",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-role",
    title: "Manage Role",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-settings",
    title: "Manage Settings",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-social-media-link",
    title: "Manage Social Media Link",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-sponsers",
    title: "Manage Sponsers",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-tell-us-form",
    title: "Manage TellUs Form",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-tell-us-section",
    title: "Manage TellUs Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-user",
    title: "Manage User",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-volunteers",
    title: "Manage Volunteers",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  },
  {
    path: "/dashboard/manage-volunteers-section",
    title: "Manage Volunteers Section",
    icon: "mdi mdi-equal",
    class: "",
    extralink: false,
    submenu: [],
  }
 
 
];
